apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-usuarios-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-usuarios-server
  template:
    metadata:
      labels:
        app: ms-usuarios-server
    spec:
      containers:
      - image: 4xe1/usuarios:latest
        name: usuarios
        ports:
        - containerPort: 8001
        env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios-server
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios-server
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios-server
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ms-usuarios-server
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-usuarios-server
                  key: password
            - name: CURSOS_URL
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios-server
                  key: curso_url
#        readinessProbe:
#          httpGet:
#            path: /actuator/health/readiness
#            port: 8001
#            scheme: HTTP
#          initialDelaySeconds: 5
#          periodSeconds: 20
#          timeoutSeconds: 10
#        livenessProbe:
#          httpGet:
#            path: /actuator/health/liveness
#            port: 8001
#            scheme: HTTP
#          initialDelaySeconds: 10
#          periodSeconds: 30
#          timeoutSeconds: 10
#        resources:
#          requests:
#            memory: "256Mi"
#            cpu: "200m"
#          limits:
#            memory: "400Mi"
#            cpu: "350m"