version: "3.9"	
services: 
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: db-ms-docker-kube
    volumes:
      - data-postgres:/var/lib/postgresql/data 
    restart: always
    networks:
      - spring
          
  ms-cursos-server:
    container_name: ms-cursos-server
    image: 4xe1/cursos
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: db-ms-docker-kube
      DB_USERNAME: postgres
      DB_PASSWORD: sasa
      USUARIOS_URL: ms-usuarios-server:8001
    networks:
      - spring
    depends_on:
      - postgres14
      - ms-usuarios-server
    restart: always
  
volumes:                                              
  data-postgres:
    name: data-postgres
networks:
  spring:
