apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: ms-gateway-server
  template:
    metadata:
      labels:
        role: ms-gateway-server
    spec:
      containers:
        - name: ms-gateway-server
          image: 4xe1/gateway:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: ms-gateway-server
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    role: ms-gateway-server